### ISSUE TITLE
www command doesn't appear to allow you to change the interface

### ISSUE THREAD

**Issue by bentasker** [mailpile/Mailpile#1162] opened 2014-12-24 10:09 UTC
I might be misreading the docs, but it looks like 'www' won't allow you to change the interface/port

    mailpile> help www
   
    Commands:
       www [<host:port>]                                      Just run the web server

    mailpile> www 192.168.1.90:1181
    Elapsed: 0.003s (www: Started the web server on http://localhost:33411/)
    
    OK: Started the web server on http://localhost:33411/

Also tried as root. I don't see anything being logged to suggest it's failing to bind to the specified port and then falling back. Have also tried specifying the host as 0.0.0.0 (e.g. bind to all interfaces)

The relevant lines of the config file are

    ;http_host = localhost       ; (default) Listening host for web UI
    ;http_port = 334411           ; (default) Listening port for web UI

Configuring the host and port in the config file does work though;

    http_host = 0.0.0.0       ; (default) Listening host for web UI
    http_port = 80           ; (default) Listening port for web UI

Tested with both release/beta and master branches on CentOS 6

**Comment by BjarniRunar** [comment] 2015-01-15 23:59
The issue is that by the time you hit the interactive CLI, the web server has already started and it's too late to tell it to start up somewhere else. If you do this, it works:

./mp --www=127.0.0.2:12345 --interact

This does work as intended, but I'll agree it's confusing. I'm not sure whether the docs should be fixed or the command tweaked to tear down the webserver and restart it in the new place...

**Comment by BjarniRunar** [comment] 2015-01-16 00:00
And if we tear down and restart... should we update the config so it stays on the new host/port when restarted with no arguments?

**Comment by bentasker** [comment] 2015-01-16 00:06
Personally, if I'd given it an interface and port through the CLI, I'd probably expect it to honour that in future (or at least to have a command/argument exposed so that I could specify that).

As the command is available within the CLI, tearing down and restarting would be the way forward IMO

**Closed** 2015-01-18 19:14 UTC

**Comment by BjarniRunar** [comment] 2015-01-18 20:16
I implemented a tear-down/restart, updating the config iff starting the web server in the new location succeeds.
