### ISSUE TITLE
Improve HTTP Error code messages in UI

### ISSUE THREAD

**Issue by Pectojin** [mailpile/Mailpile#2220] opened 2019-06-04 17:04 UTC
When attempting to uploade images that are too large the backend correctly returns a 413 Entity Too Large error, but the frontend displays a very generic error message. 

Returning the HTTP message would be pretty helpful :)

<img width="428" alt="Screenshot 2019-06-04 at 19 00 25" src="https://user-images.githubusercontent.com/1561484/58898732-82bf5000-86fb-11e9-9c23-699720b2c0a8.png">
<img width="248" alt="Screenshot 2019-06-04 at 18 59 46" src="https://user-images.githubusercontent.com/1561484/58898651-54da0b80-86fb-11e9-93f0-841cf8f1f1f0.png">

**Comment by h3artbl33d** [comment] 2019-06-15 19:32
This is a good idea. But, I guess the 413 error came from your reverse nginx proxy?

**Comment by Pectojin** [comment] 2019-06-15 20:03
Oh, I hadn't thought of that. 

It may be the cause of the actual issue. I just compressed the images instead of investigating, though. 

This issue is definitely only about the feature suggestion to improve visibility in the UI :)

**Comment by h3artbl33d** [comment] 2019-06-17 20:04
I agree with that one. I am not a member of the Mailpile project, though I am trying to help out other users with issues and might contribute toward further development in the future.

The reason for spotting that this is most likely a nginx issue is rather simple: I ran a reverse proxy before and experienced the same issue. It also can occur if you try to upload an attachment that is too big.

I used this `server` block for putting nginx in front of Mailpile: [mailpile.conf](https://gist.github.com/h3artbl33d/e43f087665f6eeb12f3871e6c39e12b1). It uses TLS and some securityheaders - on the local network.

It might be somewhat... paranoia. That is the way I roll.

**Comment by BjarniRunar** [comment] 2019-07-11 00:15
Thank you for reporting this, but if I understand correctly, the issue is that nginx is generating an error condition that Mailpile does not expect, and so the UI is unhelpful?

I don't think it's reasonable to expect Mailpile to gracefully handle and interpret and explain all the errors that can be injected by intermediate proxies; the place to fix this is in the nginx config. So I'm going to close this. Please feel welcome to disagree and try to convince me otherwise if you feel I'm wrong about this. :smiley_cat:

**Closed by BjarniRunar** 2019-07-11 00:15 UTC

**Comment by Pectojin** [comment] 2019-07-11 00:42
I don't think it matters why the errors happens. We're seeing a notification say there is an error but refusing to say what the error is.

It doesn't have to do anything but pass the error up, such as changing from `err.message` to `err.message err.code` here: https://github.com/mailpile/Mailpile/blob/babc3e5c3e7dfa3326998d1628ffad5b0bbd27f5/shared-data/default-theme/html/jsapi/compose/attachments.js#L203

**Comment by BjarniRunar** [comment] 2019-07-11 20:32
I totally agree and have merged your PR. Thank you for taking the time to discuss and contribute!

**Comment by Pectojin** [comment] 2019-07-11 20:44
Thanks for dealing with me ;)
