### ISSUE TITLE
[Question]: multi-user support?

### ISSUE THREAD

**Issue by prologic** [mailpile/Mailpile#1564] opened 2016-01-31 21:11 UTC
How does multi-user support work in Mailpile at the moment? I spun this up via [staannoe/mailpile](https://hub.docker.com/r/staannoe/mailpile/) using [Docker](https://www.docker.com) and [adaline/dockermail](https://github.com/adaline/dockermail) as the "Mail Server" backend.

One thing that was immediately lacking (*I noticed*) was the ability to authenticate against the IMAP/dovecot backend and have multi-user Mailpile on an single instance? I could be missing something though :)

**Comment by prologic** [comment] 2016-01-31 22:10
Just read through #820 -- This isn't *quite* what I had in mind for a multi-user environment :) My guess is that Mailpile's current architecture is single-user designed?

**Comment by BjarniRunar** [comment] 2016-02-01 01:08
@prologic correct, Mailpile is designed as a desktop mail client, not something for shared hosting.

In fact, we're moderately hostile towards the shared hosting scenario, as we feel as a matter of principle that people should store their data themselves, not leave it on 3rd party hosts. Mailpile is specifically not a project to enable the next GMail clone, it's a decentralization and privacy project.

**Comment by prologic** [comment] 2016-02-01 01:29
So the "ideal" use-case and deployment here would be to spin up a Mailpile instance per user; possibly on different sub-domains (*if that's what one wanted*). e.g:

- John Doe https://john.doe.com/
- Sarah Doe https://sarah.doe.com/

Right? This kind of makes Mailpiile (*in that case*) similar in style/design to [Cozy](https://cozy.io/en/) but where Cozy has more apps/integrations and is written in NodeJS :)

**Comment by BjarniRunar** [comment] 2016-02-03 00:32
@prologic That's certainly one good way to do it.

In order to save people the hassle of complicating DNS and allowing people to share an SSL cert, the Apache integration we've implemented uses the URL path: /mailpile/<user>/. Behind the scenes there is a Mailpile process for each user and Apache is just proxying.

**Comment by prologic** [comment] 2016-02-03 05:49
Yeah I see. I haven't played with the apache user feature yet. Thanks!

**Comment by BjarniRunar** [comment] 2016-02-04 10:04
You're welcome! I'm closing this issue, feel free to reopen or file a new one if you have more to discuss.

**Closed by BjarniRunar** 2016-02-04 10:04 UTC

**Comment by npodbielski** [comment] 2018-12-23 18:36
> In order to save people the hassle
of configuration you force them to do more configuration i.e. to use mailpile with private mail server you force user to install multiple instances of mailpile.  :)
This is ridiculous. If I would want single user, secure, open source mail client I can just use Thunderbird. I thought that is alternative to Squirrelmail. Oh well... I just lost like an hour to configure it because it is not mentioned even once in readme or main page of a project... :)

**Comment by poiNt3D** [comment] 2022-04-08 15:33
Sorry for intruding the isuue tracker
@npodbielski Have you found any multiuser web email client that can store a copy of all emails?

**Comment by npodbielski** [comment] 2022-04-08 15:39
Wow. After for years I do not remember (exactly) what this was about. I think I was migrating from Windows mail server to something linux based. Mailpile was a test.
I am using mailcow right now. It have integrated SOGO instance, and SOGO can be configured with other (non mailcow) IMAP emails. I configured everything there and I am happy with it so far.

**Comment by poiNt3D** [comment] 2022-04-08 15:40
@npodbielski Thank you, i will try SOGO.

**Comment by prologic** [comment] 2022-04-09 08:48
@poiNt3D If you give me some time I will still build a multi-user setup for Mailpile.

I quite like Mailpile and given the design choices, I don't think it's that hard to do. I agree with the author's design choices here and I respect that (a lot) in fact I do exactly the same thing in two of my other projects (a decentralised, self-hosted social media and instant messenger).

@BjarniRunar I _think_ we can close this. I will come up with something that work for me Infra and share my setup with this project and community soon™ Where's the best place to contribute said setup? (Closing this issue as there is nothing to do on the project side...)

**Comment by prologic** [comment] 2022-04-09 08:48
(Actually I don't seem to be able to close my own issue :/

**Comment by poiNt3D** [comment] 2022-04-09 11:21
@prologic  Are you going to fork the project? 
Btw, the issue is already closed :- )
