### ISSUE TITLE
IOError Traceback on quit

### ISSUE THREAD

**Issue by JocelynDelalande** [mailpile/Mailpile#1925] opened 2017-08-28 13:38 UTC
Sometimes (frequently) I'm getting this traceback on exit.

```OK: Shutting down...
Traceback (most recent call last):
  File "/home/jocelyn/dev/Mailpile/mailpile/commands.py", line 581, in _run_sync
    return self._finishing(command(self, *args, **kwargs))
  File "/home/jocelyn/dev/Mailpile/mailpile/commands.py", line 579, in command
    return self.command(*args, **kwargs)
  File "/home/jocelyn/dev/Mailpile/mailpile/app.py", line 158, in command
    Interact(session)
  File "/home/jocelyn/dev/Mailpile/mailpile/app.py", line 120, in Interact
    readline.write_history_file(session.config.history_file())
IOError: [Errno 22] Invalid argument

interact error: Failed: interact 
59a04d85-00010-128a=InteractCommand:c interact: Failed: interact 
Elapsed: 0.001s (interact: Failed: interact )
Traceback (most recent call last):
  File "./mp", line 14, in <module>
    Main(sys.argv[1:])
  File "/home/jocelyn/dev/Mailpile/mailpile/app.py", line 247, in Main
    readline.write_history_file(session.config.history_file())
IOError: [Errno 22] Invalid argument
```

**Comment by BjarniRunar** [comment] 2017-08-28 13:42
Interesting, perhaps we're missing a dependency? I think Mailpile will start up without readline, but it looks like that got overlooked elsewhere.

**Comment by JocelynDelalande** [comment] 2017-08-28 13:52
@BjarniRunar what makes you think it is related to missing readline dependency ?

**Comment by BjarniRunar** [comment] 2017-08-29 11:04
Just a guess. Could well be wrong; either way, making those calls tolerate errors without exploding is the right thing to do, and not complicated (try/except/...). It'd be nice to know why it's failing in your case too though.

**Comment by priyanshsaxena** [comment] 2017-12-21 07:29
@BjarniRunar @JocelynDelalande any pointers on how to reproduce this ?

**Comment by JocelynDelalande** [comment] 2017-12-21 10:31
@priyanshsaxena well, just almost every time I quit mailpile, actually.

I'm on debian strech, I'm using debian version of python dependencies (no virtualenv).

**Comment by BjarniRunar** [comment] 2017-12-30 16:38
I've got this fixed in my local tree, just need to push it up. Sorry about the delay!

**Closed** 2018-03-08 12:56 UTC
Labels: Back End, Bugs, Low Hanging Fruit
