### ISSUE TITLE
Implement way to Edit Contacts

### ISSUE THREAD

**Issue by miguelbernadi** [mailpile/Mailpile#1011] opened 2014-09-26 06:58 UTC
There is no way to edit or delete contacts from the HTML UI. For editing, a button should be available on the details page.

Also, as is possible to mass-select contacts in the contacts page, it would be nice to be able to do some kind of action, like mass-delete the selected contacts.

Also, the possibility to merge contacts (by having two or more contacts merge into a new one changing the name and aggregating mails, keys, etc.). Intended for finding out different alias are in fact the same person.

**Comment by danger89** [comment] 2018-04-03 21:40
I also woild like to see a basic Contact manager.. how can I manage my contacts? Is this already part of 1.0?

**Comment by BjarniRunar** [comment] 2018-04-04 13:57
Closing this as it is a duplicate of #999. Please @danger89, if you are going to me-too every single issue you agree with in the repo, maybe use the emoticon reactions instead of posting a comment? You're spamming my notifications.

**Closed by BjarniRunar** 2018-04-04 13:57 UTC
Labels: Front End

**Comment by danger89** [comment] 2018-04-04 16:10
Sorry about the spamming I agree. Atleast we clean-up the backlog this way.
