### ISSUE TITLE
[Release Beta III] Email Account configuration gone after exiting mailpile

### ISSUE THREAD

**Issue by hugoroy** [mailpile/Mailpile#1362] opened 2015-08-03 10:24 UTC
Hello,

First, some context: I'm running mailpile through Arch Linux. I
installed https://aur4.archlinux.org/packages/mailpile-git/ and I
modified a line in the PKGBUILD to use the ‘release/beta’ branch.
1. Launch ‘mp’ (in the terminal)
2. Configure mailpile
3. “E-mail Accounts”: +Add Account
   3.1. Configure
4. Point Mailpile to local Maildir mailboxes (I was confused with the
   browse "files" or "local mailbox" distinction), test stuff, send
   email, etc. (it all works, great job!)
5. Close tab (I did not log out). Exit mailpile (in the terminal).
6. Repeat step 1

The configuration is not all gone. I still have my indexed email in
the left pane, with correct mailboxes etc.

But I'm back with no Email account configured. So I can't compose any
email, I need to set up an account again.

I stopped there, filed this bug report (if this is a duplicate, sorry,
I couldn't browse the Github issues efficiently) and did nothing else.
So any info on how to debug this is appreciated (could not find
relevant information by quickly going through the git repos' doc/ --
maybe I missed it :-)

**Comment by hugoroy** [comment] 2015-08-03 16:11
FYI, I could not produce the bug a second time, with the minor difference that before step 5, I logged out of the session during which I configured the email account. I don't know if that makes a difference.

**Comment by BjarniRunar** [comment] 2015-08-03 18:21
This is strange and worrying. It basically sounds like it failed to write out your configuration. Not sure how to debug this further, especially since you couldn't reproduce.  I'll double-check to make sure all the account setup steps correctly save the config, but that's about all I can think of at this point...

**Comment by hugoroy** [comment] 2015-08-03 18:30
Yes, unfortunately there was no useful information from the terminal and I was just testing. By the way, are there any option I can give to launch mp with more debug information? That might have been useful.

I'd be happy to delete everything and test again.

**Comment by BjarniRunar** [comment] 2015-08-03 18:33
mailpile> set sys.debug = log sources  
mailpile> eventlog/watch  

... might help. :-)  you'll need a decent scrollback buffer in your terminal to catch all the output.

**Comment by herrniemand** [comment] 2015-10-03 03:29
@hugoroy Same. Tested on **0.5.2 Beta III** - updated release. What funny is on stream development branch works like candy... except this annoying blur. XD

**Comment by BjarniRunar** [comment] 2017-03-01 00:24
Closing this, it's obsolete and we never managed to reproduce. Thanks for filing!

**Closed by BjarniRunar** 2017-03-01 00:24 UTC

**Comment by hugoroy** [comment] 2017-03-01 22:41
↪ Bjarni Rúnar Einarsson / mars 1, 2017 1:24:
> Closing this, it's obsolete and we never managed to reproduce. Thanks for filing!

You're welcome, keep it up! /-)
