### ISSUE TITLE
Multiple issues with mail source setup in Beta II

### ISSUE THREAD

**Issue by cbz20** [mailpile/Mailpile#1221] opened 2015-01-23 22:51 UTC
I am trying to setup my gmail account as a mail source after a fresh installation of Beta II, but I encounter multiple issues:

After the initial setup, I got a message "Not connected to server". Nonetheless, I clicked "configure now" and I got the following screen:

![mailsources_before](https://cloud.githubusercontent.com/assets/9016969/5883312/2dd34f96-a349-11e4-88d7-651c497a1318.GIF)

The two redacted entries above are the two parent labels of my gmail account, so the connection did not fail completely. I pressed "save" and mailpile started downloading emails. However, when I tried to configure the labels again, I got the following weird screen:

![mailsources_after](https://cloud.githubusercontent.com/assets/9016969/5883313/2ddf23e8-a349-11e4-917d-4aa27f6875e8.GIF)

I first thought I should have waited longer for the message "Not connected to server" to change into something more optimistic, but I could reproduce the behaviour above for a second mail source (the same gmail account, disabling the first source):

![mailsources](https://cloud.githubusercontent.com/assets/9016969/5883305/1a56560c-a349-11e4-9e0a-d298ea241950.GIF)

I did not encounter this problem in Beta I and after #1180 was fixed, mailpile could also see all of my gmail labels. This looks like a step in the wrong direction. Or am I doing something wrong?

**Comment by BjarniRunar** [comment] 2015-06-08 14:09
Thank you for taking the time to file this issue. After reviewing all the feedback, I decided to try a different approach to initial account creation and setup - so all this code is going away, to be replaced by other things.

As a result, this issue won't be fixed directly... but hopefully the new system will address the root cause and work better for you and others.

**Closed by BjarniRunar** 2015-06-08 14:09 UTC
