### ISSUE TITLE
boxes too small for content in '/browse'

### ISSUE THREAD

**Issue by simonsmiley** [mailpile/Mailpile#1441] opened 2015-11-06 10:40 UTC
The boxes are too small for my email address. 
the settings icon hides some of the text, and the IMAP entry is completely hidden

**Comment by Epse** [comment] 2016-10-24 19:40
This seems to be an issue with Rebar. Looked into it, hard to fix without forking Rebar

**Comment by BjarniRunar** [comment] 2016-10-25 11:34
Switching to a completely different layout on that page is absolutely an option.

It doesn't need to be boxes, and in fact I'm not even sure the boxes are a good idea. That's just what I had to work with - I'm mostly working on the backend, getting the functionality in place. The idea was to sort of emulate the icon-view of a file manager, but a more boring list-based view would still get the job done.

**Comment by Epse** [comment] 2016-10-25 14:53
I'll look into it

**Comment by Epse** [comment] 2016-10-25 18:30
Going through it I found that `{{ info.display_name }}` has a bunch of whitespace before and after it. In fact pretty much anything, include icons which are dumped into templates seem to have a lot of whitespace before and after (spaces). Any reason for this?

**Comment by BjarniRunar** [comment] 2016-11-02 10:00
Whitespace shouldn't matter when rendering the HTML. If you are looking at what your web browser sees, then the whitespace is probably caused by the templating engine. I don't think it's worth worrying about.

**Comment by Epse** [comment] 2016-11-02 12:08
I think it is, because it is inside the tags and makes tables go weird.
When I'm back home I will look into the engine.

**Comment by Epse** [comment] 2016-11-04 09:52
Did some research, seems to be a Jinja "feature" of sorts. Adding a *-* to the start of the tags should fix that. Now I can make it a table! Hurrah

**Comment by Epse** [comment] 2016-11-29 16:34
I have a almost-done fix for this one. Just one question: I can't seem to find the source for the `settings(attr, info)` function anywhere, it is being called to create a link to open a modal with settings, however the `a` tag is always surrounded with a div with class `right` which you really don't want in a table. Any way to get around that?

**Closed** 2016-11-30 13:03 UTC
Labels: Bugs
