### ISSUE TITLE
Webdav contacts

### ISSUE THREAD

**Issue by blackcrack** [mailpile/Mailpile#1386] opened 2015-08-21 17:59 UTC
Hi,

i use openmandriva (.org) (the real successor of Mandrake but in the hands of Community now)  
as my webserver blackysgate.net and i have there running owncloud 
and use it for different web applications and for my Thunderbird also,
would be nice if be able to use webdav's contacts  in Mailpile
(i dont know if this currently already possible but short ask cost nothing i guess :) )

best regards
Blacky

**Comment by BjarniRunar** [comment] 2015-08-23 22:21
This is a duplicate of #104, I think. :-)

**Closed by BjarniRunar** 2015-08-23 22:21 UTC
