### ISSUE TITLE
Template error

### ISSUE THREAD

**Issue by ferdiga** [mailpile/Mailpile#1709] opened 2016-11-29 18:33 UTC
v 1.0.0.rc
after creating a new tag i can not open the message view any more 
"Template error" is displayed instead

**Comment by BjarniRunar** [comment] 2016-11-29 18:58
I appreciate your report, but this is not enough detail for me to do anything about this. I am able to create new tags just fine in my pile.

What was the name of the tag you created? What tag settings did you choose?

What version of the code - note that v1.0.0rc doesn't tell me anything, I need to know what the last commit pulled from github was, because everything is changing constantly.

**Comment by ferdiga** [comment] 2016-11-29 19:07
sorry the report is poor, .... I didn't find a trace

last commit is
commit ff2952cd373eafae7350beff03416a72e7777a42
Merge: 8ae8eb7 bfdc0ed
Author: Bjarni Rúnar Einarsson <bre@klaki.net>
Date:   Sun Nov 27 20:16:23 2016 +0100
    Merge pull request #1697 from mathroc/master
        fix Dockerfile (& upgrade ubuntu)

What was the name of the tag you created? 
Done
What tag settings did you choose?
I suppose it was
"Behave as attribute" and ticking "Display in toolbar"

**Comment by ferdiga** [comment] 2016-11-29 19:38
BTW I can display the profile page
./mailpile/profiles/

**Comment by ferdiga** [comment] 2016-11-29 20:50
the error is here (I added "A" to the error message)
line 513 inmailpile/ui.py

        except (UndefinedError, ):
            tpl_esc_names = [escape_html(tn) for tn in tpl_names]
            return self._render_error(cfg, {
                'error': _('Template error A'),
                'details': ' or '.join(tpl_esc_names),
                'traceback': traceback.format_exc(),
                'data': alldata
            })

**Comment by ferdiga** [comment] 2016-11-29 20:57
I added a debug info

```
        except (UndefinedError, ):
            tpl_esc_names = [escape_html(tn) for tn in tpl_names]
            return self._render_error(cfg, {
                'error': _('Template error A ' + tn ),
                'details': ' or '.join(tpl_esc_names),
                'traceback': traceback.format_exc(),
                'data': alldata
            })
```

Template error A search/index.html
Does this help?

**Comment by BjarniRunar** [comment] 2016-11-29 21:25
Thank you for the extra details!

I need to write some debugging guidelines for helpful folks like you. :-)  I'm still lost, probably the most useful thing you could do now is to (at the mailpile> prompt), type:

    set sys.debug = log http

This will enable debug output, including traces in the browser when templates fail to render. That should help us narrow things down a bit. It will also print stack traces to the console, which can be invaluable as well (watch out as they may scroll up quickly, Mailpile becomes very verbose with debuggin switched on).

**Comment by Comarco** [comment] 2016-12-03 17:04
I get the same problem with cloned repos, here is a fist debug message that could be usefull.

```
Template error

search/index.html
TRACEBACK:

Traceback (most recent call last):
  File "/home/test/src/Mailpile/mailpile/ui.py", line 505, in render_web
    return template.render(alldata)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/test/src/Mailpile/shared-data/default-theme/html/search/index.html", line 1, in top-level template code
    {% extends "layouts/" + render_mode + ".html" %}
  File "/home/test/src/Mailpile/shared-data/default-theme/html/layouts/full.html", line 1, in top-level template code
    {% extends "layouts/content.html" %}
  File "/home/test/src/Mailpile/shared-data/default-theme/html/layouts/content.html", line 3, in top-level template code
    {%- block content_top %}
  File "/home/test/src/Mailpile/shared-data/default-theme/html/layouts/content.html", line 6, in block "content_top"
    {% block contenttools %}
  File "/home/test/src/Mailpile/shared-data/default-theme/html/layouts/content.html", line 13, in block "contenttools"
    {% include("partials/tools_search.html") %}
  File "/home/test/src/Mailpile/shared-data/default-theme/html/partials/tools_search.html", line 88, in top-level template code
    {%-     do search_actions.append('
UndefinedError: 'dict object' has no attribute u'#4D4D4D'
```

**Comment by MartinNowak** [comment] 2017-03-24 17:34
For me it was apparently an issue w/ old configuration data.

**Comment by BjarniRunar** [comment] 2017-03-25 23:28
What @Comarco has reported should only happen if tags have colors configured as hex values, instead of the names which are generated by all of the existing Mailpile code. So that issue at least is almost certainly old data as @MartinNowak suggests.

I don't think that's the same problem as was initially reported here, but since no further details have been provided I am going to have to close this as unreproducable/unfixable.

**Closed by BjarniRunar** 2017-03-25 23:28 UTC
