### ISSUE TITLE
Long names are printed over the mail-address 

### ISSUE THREAD

**Issue by ferdiga** [mailpile/Mailpile#1633] opened 2016-10-01 18:29 UTC
1.0.0.rc0
difficult to read - usability

![overlay1](https://cloud.githubusercontent.com/assets/6248560/19016279/a28e27cc-8815-11e6-8182-e7a3facc04da.jpg)

**Comment by BjarniRunar** [comment] 2016-11-22 17:53
This is a duplicate of #1477, closing.

**Closed by BjarniRunar** 2016-11-22 17:53 UTC
Labels: Front End, Low Hanging Fruit
