### ISSUE TITLE
encryption is broken

### ISSUE THREAD

**Issue by pravi** [mailpile/Mailpile#1360] opened 2015-08-02 09:46 UTC
I can't encrypt a message even when I have the corresponding key.
![screenshot from 2015-08-02 15-14-33](https://cloud.githubusercontent.com/assets/708222/9025609/47713b72-3929-11e5-93eb-eea081339bd3.png)

see screenshot. It is a critical bug.

**Comment by pravi** [comment] 2015-08-02 09:50
I have been sending encrypted mails to this contact using thunderbird on the same system for weeks now.

**Comment by pravi** [comment] 2015-08-02 09:58
this is git pulled today on debian sid

**Comment by pravi** [comment] 2015-08-02 09:59
It can't be an issue with gpg itself as I was able to sign a message and it could verify it.

**Comment by hugoroy** [comment] 2015-08-03 10:41
I have the same issue (pulling the release/beta branch).

PS: you should update your issue's title, it's not self explanatory. Maybe something like:
"Cannot send encrypted email even though mailpile finds my contact's encryption key"

**Comment by bnvk** [comment] 2015-08-03 10:49
@hugoroy @pravi can you give more details on what happens in this scenario? Are you clicking on the orange lock and then Mailpile shows you the "Cannot Encrypt" dialogue?

**Comment by hugoroy** [comment] 2015-08-03 14:26
So, after re-setting an email account (see issue #1362) and selecting
"always sign outgoing email" as a setting.

1. Compose
2. To: an alternate email address of mine, which I have in my GnuPG
keyring and which I trust.
3. The signing icon is green but the encryption icon is grey.
4. Click on the grey lock:

          You are missing encryption keys for the following contacts

5. Click "Find Encryption Keys"
6. Get a  five-green-star key for my contact and:

          This key is in your keychain

7. Actions, either "Send Unencrypted" or "Try Again" (or close the
modal)
8. The encryption icon which was gray in step 3 is now orange.




-- 
Hugo Roy – Free Software Foundation Europe https://fsfe.org/about/roy
 
Please use cryptography for email: see https://emailselfdefense.fsf.org/en/
Merci d’utiliser la cryptographie pour l’email : voir https://emailselfdefense.fsf.org/fr/

**Comment by bnvk** [comment] 2015-08-03 14:35
@hugoroy thanks for reporting. I have a hunch this is a front-end bug. Just to be thorough, can you check your JS console and paste in any errors you see there?

**Comment by hugoroy** [comment] 2015-08-03 15:28
Ha, when I tried again, the key lock is now green, even with another contact. So, I'm sorry there are no useful info in the console AFAICS.

**Comment by pravi** [comment] 2015-08-03 16:12
Now the lock is getting green when you click, but a pop up message at bottom says. 

"Could not encrypt message". Nothing on terminal or javascript console.

@hugoroy did encryption work? Were you able to send encrypted?

**Comment by pravi** [comment] 2015-08-03 16:13
Failed on both Google Chrome 38.0.2125.104-1 and Iceweasel 38.0.1-5 (debian sid amd64)

**Comment by pravi** [comment] 2015-08-03 16:18
I could encrypt when I tried again. I think it is related to unlocking the secret key. It worked after I successfully sent a signed mail.

**Comment by pravi** [comment] 2015-08-03 16:19
I could see this on the console now

```
<StreamWriter(gpgi-output(gpg --status-fd=2 --no-use-agent --enable-progress-filter --batch --verbose --with-colons --utf8-strings --clearsign --armor --local-user 2A7974AE2FC152D77867DA4ACE1F9C674512C22A), started daemon 140606751893248)>(gpgi-output(gpg --status-fd=2 --no-use-agent --enable-progress-filter --batch --verbose --with-colons --utf8-strings --clearsign --armor --local-user 2A7974AE2FC152D77867DA4ACE1F9C674512C22A)/write): 75 bytes left
Traceback (most recent call last):
  File "/home/pravi/forge/mailpile/Mailpile/mailpile/crypto/gpgi.py", line 393, in writeout
    fd.write(line)
IOError: [Errno 32] Broken pipe

```

**Comment by BjarniRunar** [comment] 2015-08-03 18:01
Question: are you guys trying to encrypt TO YOURSELF? :-)

This is important, as that follows a different code path from encrypting to other people.

**Comment by hugoroy** [comment] 2015-08-03 18:06
Yes, I was testing with MYSELF :-) and then I tried with others.

(I actually did not test send the encrypted email, but I just tested until the interface said it was okay to send encrypted email)

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by pravi** [comment] 2015-08-03 18:08
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

On Monday 03 August 2015 11:31 PM, Bjarni Rúnar Einarsson wrote:
> Question: are you guys trying to encrypt TO YOURSELF? :-)

No, I was sending to other people.
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJVv64rAAoJEM4fnGdFEsIqeIIP/RrQSvwGpwGOcxVVYWsQ5q4P
viJuV5Mb1nRp3oCwTYg08HIW9U6ZNMz/yju+xVCKB7EetifMuo1A0K+ZPPfn78Rj
VV3Qh2S/ytQVQLNH0SCRHK9F8jAeBwPurS5h4pjETsvcU6vkydifKWxn5DCISu0G
MKpg0MXNptq8h/fcoYzJYYv5PFt7dhJ/srrhcoLl8F4dtgxOoT4qU6SYMoXQE/yX
N6Om4MeK4DjZ4gVBoY5JVM75T6/pMvuWPrwfDn+EfZz3QkhFm74zQ9W/VvYho0p0
wHSe3aDaQgsbLr7fT+YTUkIJtyR0RX/LmXjeY4WIUU4ZaxIXWITl9BTXVdXHcFsd
rY5wthwPlG8HtpT4dgBQZbi8GysZpOfmqyacXTA/VKgcuiWrE7KXwXoWu/vjDaxi
w9Az47ZPrGmn+MWw8+dLqXQH8sVx1/N0THlkRmcmhRF/PsUXT2f2bKOp7Jk5AdGV
qqOIoVventSWo7F5yRRXIV9ZTwu3FYVaTZdJaTvqxJ2GB7akuHcTYRAlUN+6Ovvu
tVzgF+5Zv/Clr6cmP9hFqLJqyQB/wUlWHgdl4sAQp+e5uO+qaTbN99/oxbKjwOPJ
K99nIrwwqiqvQOwn8NJZiiPiX223472/O9TeUWnFgPxVxan6ZpicakxDCc0QV7Vq
ODiIO3YvGXoG8zJ8j3AM
=LMMK
-----END PGP SIGNATURE-----

**Comment by BjarniRunar** [comment] 2015-08-04 15:15
I suspect both of you may be running gpg v2, not gnupg 1.4.  Can you verify by running in the shell? gpg --version

**Comment by hugoroy** [comment] 2015-08-04 15:16
That's right. I'm running 2.1.

(I haven't checked but from what I recall...)
-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by BjarniRunar** [comment] 2015-08-04 17:18
@pravi OK, in your case Mailpile should use gpg 1.4, so that's not the cause of your issues.

However, @hugoroy, Mailpile doesn't yet work reliably with gpg2, we have #1133 filed for that.

**Comment by hugoroy** [comment] 2015-08-04 17:37
@BjarniRunar Just checked. I only have 2.1.6. Looking forward to be able to use gpg2 :-)
Are all features relying on gpg impacted by this or only some of them? If you need help debugging with gpg2, I'd be happy to contribute.

**Comment by BjarniRunar** [comment] 2015-08-04 17:50
@hugoroy The impact is unknown at this time. Some things appear to work, but it's flaky. Documenting what works and what doesn't would actually be an amazing start to that work. However, in particular I am pretty sure the way we handle passphrases tends to make gpg2 unhappy, so most actions involving signatures are expected to break.

**Comment by pravi** [comment] 2015-08-05 06:55
@BjarniRunar since I can encrypt after sending a signed message first, it is clearly not a gpg issue but mailpile's.

**Comment by BjarniRunar** [comment] 2015-08-06 17:31
After looking around a bit, I think this is probably caused by limitations to how the gpg keychain is synchronized with Mailpile's contacts. There are cases, especially on a fresh install or to do with your own personal keys, where keys on your keychain may not be recognized by Mailpile's composer, even if the key search feature can find them.

I am going to close this issue, but have filed a new one to track those problems specifically: #1370

**Closed by BjarniRunar** 2015-08-06 17:31 UTC
Labels: Bugs, Front End

**Comment by arhue** [comment] 2016-10-27 10:10
I'm getting a similar issue. GPG version is 1.4.20. A public key of a different person was already imported into my public key ring from a previous install. Had to delete it for it to work. Display message was exactly the same. Not sure if it's the same bug.
