### ISSUE TITLE
`Internal error` on return from Gmail OAauth flow

### ISSUE THREAD

**Issue by paulfurley** [mailpile/Mailpile#2157] opened 2018-10-23 18:01 UTC
I went through the OAuth flow for paul@fluidkeys.com which uses G Suite. On return I got an internal error from mailpile:

![image](https://user-images.githubusercontent.com/254290/47380629-cbd70c80-d6f5-11e8-81f9-aaf8d80eed35.png)

I got the following output in the developer console (though I don't think it's helpful):

> The character encoding of the plain text document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the file needs to be declared in the transfer protocol or file needs to use a byte order mark as an encoding signature.

Thanks!

**Comment by sbadux** [comment] 2018-10-23 18:54
Same here (Ubuntu 18.10) with a standard free gmail.com account.

**Comment by paulfurley** [comment] 2018-10-24 04:40
Apologies for lack of information in my bug report. This was on Ubuntu 16.04LTS installed from your apt repo, version: 0.99.3~1.0201806291047-1.

I looked for useful log entries in `.local/share/Mailpile/default/logs` but didn't find anything related to the internal error - is there another location I can look?

**Comment by BjarniRunar** [comment] 2018-10-24 07:16
Thank you for reporting this!

The easiest way to debug is, at the Mailpile CLI prompt (not in the browser):

    mailpile> set sys.debug = log http
    ...
    mailpile> eventlog/watch
    ...
    (press ctrl+c to return to the prompt)

That tells Mailpile to both print a bunch more junk directly to the screen, but also to disable caching of templates and [try to] tell the browser not to cache things. There are more debug tips in the DEV_FAQ file in the root of the repository.

**Comment by sbadux** [comment] 2018-10-24 18:39
> Oh, that error! I think I have already fixed this (in master). Are you running the stable/release package?

I've installed it yesterday from the Debian repositories as shown here https://www.mailpile.is/download/linux.html.

The About screen shows "Welcome to Mailpile 1.0.0rc3"

**Comment by BjarniRunar** [comment] 2018-10-24 18:47
Unless you made a specific effort to switch to the nightly repos, you're on release. I guess I should tag another RC soon to get those bugfixes shipped, GMail changed their behaviour.

**Comment by sbadux** [comment] 2018-10-24 18:54
In the page above I didn't find how to enable nightly builds. Can this be done for the repositories or I need to install a specific package? I'm just testing MailPile and I'm ok with unstable versions. I would like to get Gmail working so I can test a nightly :)

**Comment by BjarniRunar** [comment] 2018-10-24 19:19
It's just another repo - it is in the instructions, I suggest re-reading.

It should boil down to `s/release/nightly/g` in your apt sources definition files. :grin:

**Comment by sbadux** [comment] 2018-10-24 19:53
> It's just another repo - it is in the instructions, I suggest re-reading.
> 
> It should boil down to `s/release/nightly/g` in your apt sources definition files.

Sorry. I didin't see that note in the instructions, but I can confirm that the issue is fixed in the nightly

**Comment by BjarniRunar** [comment] 2018-10-25 10:19
Excellent! Thanks for the report and for confirming the fix works. It's a good reminder that our release branch needs an update ASAP.

**Closed by BjarniRunar** 2018-10-25 10:19 UTC
