### ISSUE TITLE
Crashing on SMTP insecure server (NameError)

### ISSUE THREAD

**Issue by JocelynDelalande** [mailpile/Mailpile#1845] opened 2017-05-31 06:55 UTC
since #1834 Mailpile is yelling about bad SMTP/IMAP certificates.

On IMAP, it is working fine. On SMTP, it's crashing (at sending time) instead of issuing an error :

```
mailpile> sendmail
xxxxxxxx-xxxx-xxxx=Sendit:R Sending via example.com
xxxxxxxx-xxxx-xxxx==Sendit:i Could not send mail to bugs@mailpile.is
Could not send mail to bugs@mailpile.is
Traceback (most recent call last):
  File "/home/jocelyn/dev/Mailpile/mailpile/plugins/compose.py", line 907, in command
    events=events)])
  File "/home/jocelyn/dev/Mailpile/mailpile/smtp_client.py", line 318, in SendMail
    RunTimed(300, sm_startup)
  File "/home/jocelyn/dev/Mailpile/mailpile/util.py", line 1006, in work
    result.append(func(*args, **kwargs))
  File "/home/jocelyn/dev/Mailpile/mailpile/smtp_client.py", line 260, in sm_startup
    raise InsecureSmtpError()
NameError: global name 'InsecureSmtpError' is not defined
```

**Comment by BjarniRunar** [comment] 2017-05-31 23:57
Thanks for reporting this. I'll try and get it fixed ASAP.

**Comment by BjarniRunar** [comment] 2017-06-01 12:33
There is a workaround for this.

1. Figure out the name and port of your SMTP server (mail.foo.com:465 for example). You can see this by checking the account settings.

2. Enter the HOSTNAME:PORT into the TLS certificate checker tool. The tool is found by visiting the event log (click Notifications in the lower-right corner), and then click "TLS certs" from the toolbar.

That will allow you to add a security exception and sending mail should work again.

**Comment by BjarniRunar** [comment] 2017-06-01 12:33
... detecting the issue from the event log and providing a prompt to automate the above is in the works.

**Comment by JocelynDelalande** [comment] 2017-06-03 12:45
Thanks for your help :-)

I'm trying to workaround:

> Enter the HOSTNAME:PORT into the TLS certificate checker tool. The tool is found by visiting the event log (click Notifications in the lower-right corner), and then click "TLS certs" from the toolbar.

If I enter my.server.example.com:587 in the box, then validate, I get 

    Failed to fetch certificate
    [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:581)

A bug or am I doing something wrong ?

**Comment by BjarniRunar** [comment] 2017-06-07 10:10
@JocelynDelalande Hmm... I think you've found another limitation of the current code.

Port 587 is "submission", which is just an alternate location for clear-text SMTP (same as port 25). Any security is bolted on using the SMTP STARTTLS verb, after the initial clear-text handshake.

The TLS certificate checker doesn't know how to do SMTP and STARTTLS, which is going to be a problem for using self-signed certs with STARTTLS. The checker probably needs to be enhanced to detect and work with STARTTLS.

The workaround for the workaround, is to see if your SMTP server is listening on port 465, which is the TLS-then-STMP port.

**Comment by BjarniRunar** [comment] 2017-06-07 10:51
@JocelynDelalande I've enhanced the cert checker to speak SMTP STARTTLS, see if it works now?

**Comment by JocelynDelalande** [comment] 2017-06-07 12:02
> @JocelynDelalande I've enhanced the cert checker to speak SMTP STARTTLS, see if it works now?

Moved to  latest master and tested, result remain the same for me (I double-checked that my mail server is up and running):
```
this.example.net : 587

Failed to fetch certificate

[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:581)
```

**Comment by largestprime** [comment] 2017-06-07 12:15
same here. but in my case the error is (trying ports, 465, 587, 993)

[Errno -2] Name or service not known

and one time, I got this, but have so far been unable to reproduce it
[Errno -5] No address associated with hostname

-- 
Daniel Yeow
+49 173 722 8769
http://www.danielyeow.com
http://darkroom.danielyeow.com

"To save the world requires faith and courage: faith in reason, and
courage to proclaim what reason shows to be true."   ~ Bertrand Russell

**Comment by BjarniRunar** [comment] 2017-06-07 14:17
I'm not happy with the spaces I see in the example up there... if you guys could out-of-band send me the actual server names you're trying to use I'll be able to debug this a lot faster. :-)

**Comment by BjarniRunar** [comment] 2017-06-07 14:18
(there should be no spaces in the hostname:port string)

**Comment by JocelynDelalande** [comment] 2017-06-07 15:09
Ok, so now adding exceptions from the eventlog view works. Thanks :-).

The initial issue remains : before manually adding an exception, mailpile still crashes with a NameError.

**Comment by BjarniRunar** [comment] 2017-06-07 15:11
I know, that's a bigger issue. The workaround needs to work anyway for the proper solution to do it's job. So these were steps in the right direction, thanks for the detailed bug reports guys.

**Comment by BjarniRunar** [comment] 2017-06-23 12:43
This should all be fixed now. Please re-open or file a new issue if I'm totally wrong. :)

**Closed by BjarniRunar** 2017-06-23 12:43 UTC
Labels: Back End, Bugs
