### ISSUE TITLE
Sending encrypted emai from Full Composer l silently fails

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#1563] opened 2016-01-30 13:36 UTC
Upon pressing "Send" of an encrypted email in a normal "full composer" view, sending fails with no UI feedback. The error in the JS console is:

```
TypeError: response.error is undefined
```

The error comes from [this line](https://github.com/mailpile/Mailpile/blob/334dfb95ffa1cecbee4e03375e6a5fa8b1652461/shared-data/default-theme/html/jsapi/compose/events.js#L146)

**Comment by bnvk** [comment] 2016-01-30 14:59
Update! I have no idea why this was failing- it was an email that was a "forward" which had these properties:

When typing a message in the "full composer" view like http://localhost:33411/message/draft/=VY9/ autosaving of recipients, subject, and message content fails to save anything. This is currently failing on a message that I am trying to forward. Oddities of note:

- Recipients, subject, and body would not save
- An attachment did save
- Message does seem to save as a Draft- navigating to msg /in/drafts/ it didn't exist
- Accessing the URL, it was there

The JSON (pre-key-unlocking) was just `status:failing` with no more of a message. After unlocking my key, the JSON response from http://localhost:33411/api/0/message/update/send/ was:

```
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
```

**Comment by bnvk** [comment] 2016-01-30 15:03
I think this is related to #1562 actually

**Comment by BjarniRunar** [comment] 2016-02-01 01:15
That seems very likely - that bug is next on my list. Thanks for reporting and digging into this; I'm going to close this as a duplicate of #1562 , please reopen if it turns out that it's still broken once I've fixed the attachment thing.

**Closed by BjarniRunar** 2016-02-01 01:15 UTC
