### ISSUE TITLE
Details link in the notification dialog does not work when non-root path is used

### ISSUE THREAD

**Issue by foursixnine** [mailpile/Mailpile#2107] opened 2018-06-20 21:31 UTC
While reporting #2106 found out that the Details link does not work either under the same circumstances: 

That is having the same configuration as reported there (#2106), once a tls connection error happens, when the user wants to click to see more details, nothing happens. and `AM: Error: error as.js:3020:9` is shown in the js console

![screenshot-2018-6-20 preferences santiago zarate s mailpile v1 0 0rc3](https://user-images.githubusercontent.com/229240/41685705-a61da3c6-74e1-11e8-8217-0fdb04d6cbcb.png)

```
    <span class="icon icon-mailsource"></span>
    <span class="text">
      <span class="message">santiago@zarate.co</span><br>
      <span class="action">Failed to make a secure TLS connection
        - <a onclick="Mailpile.certificate_error_details('services.zarate.co:143','5b2a9cbb-0018c-11fd');" data-event_id="5b2a9cbb-0018c-11fd" class="action ">details</a>
      </span>
    </span>
    <a href="#" data-type="notify" class="notification-close"><span class="icon-x"></span></a>
```

**Comment by BjarniRunar** [comment] 2018-06-21 10:39
Again, thank you for a clear and helpful bug report!

This probably has the same root cause as #2106 and the solution I describe there should apply. I'm closing this as a duplicate, but please feel free to re-open if you think I got it wrong.

**Closed by BjarniRunar** 2018-06-21 10:39 UTC
