### ISSUE TITLE
Add next/previous buttons to full message view

### ISSUE THREAD

**Issue by alescia** [mailpile/Mailpile#1256] opened 2015-03-02 15:15 UTC
Using Mailpile on Windows 7 via Chrome. 

I was wondering if there are shortcuts for going from viewing one email to viewing the next? At the moment, one has to go back to the list view before moving to the next email and viewing it, which is cumbersome.

**Comment by BjarniRunar** [comment] 2015-04-15 16:23
That functionality - going from one e-mail to the next in full viewing mode - does not yet exist, so in particular there is no keyboard shortcut for it. It would be nice to have though, editing the subject of this bug to reflect that.

**Comment by BjarniRunar** [comment] 2015-06-05 22:57
(Recent changes have made this easier to implement. I'm going to describe roughly what is required and tag this issue as Low Hanging Fruit.)

Background:

The tricky thing about "next" and "previous", is they actually depend on the context of where the user came from. If you're looking at the results of "from:bjarni subject:stuff", the "next" message has a totally different meaning from the "next" message when you were looking at "all:mail".

To deal with this sort of thing, under the hood, Mailpile keeps an internal history of recent searches and provides access to this via. a "search context" ID. This variable is exposed to Javascript as a data attribute on the search box, as well as in the search JSON itself for rendering via. Jinja.

So given the ID of the message being viewed, and the list of results (derived from the context and history), it is possible for the Python back-end to calculate the "next" or "previous" message for any context.

So to solve this:

1) The View command should be extended to calculate next/previous based on context, and include that in the raw results.
2) The View templates should have Next/Previous buttons added to the Jinja templates.
3) Any links which spawn message views from the context of a search need to have the context= variable added to the query string (or POST data)

If anyone decides to work on this, please ping me on IRC (Freenode, #Mailpile) to let me know. :-)

**Comment by axeltomasson** [comment] 2015-09-04 15:07
duplicate of #1009

**Comment by BjarniRunar** [comment] 2015-10-14 08:54
As mentioned in #1354, it would make sense to also add "back to search" functionality as part of this effort.

**Comment by BjarniRunar** [comment] 2015-12-23 01:31
Closing this, the new message view has next/back buttons. :-)

**Closed** 2015-12-23 01:33 UTC
Labels: Back End, Front End, Low Hanging Fruit
