### ISSUE TITLE
Zoho mail, not receiving 

### ISSUE THREAD

**Issue by pmeeke** [mailpile/Mailpile#1584] opened 2016-03-27 13:32 UTC
I seem to have gmail all set up and working fine. But Zoho mail I can't. I can send emails via zoho fine but receiving simply says that I have no new messages. 
Sorry updated my question, as it seems it is other imap accounts which are also timing out. All i can see is a message on the web interface saying `connection timed out`.. 

The only output I can find which may help debug this is :

```
56f7d072-30357-169f=ImapMailSource:R Connection timed out
bg/log(50): <ImapMailSource(xxxxx@xxxxx.com started 140691683137280)>: Idle: Connection timed out
bg/log(50): Traceback (most recent call last):
  File "/home/pmeeke/gits/Mailpile/mailpile/mail_source/imap.py", line 533, in _connect_imap
    conn = timed(mkconn)
  File "/home/pmeeke/gits/Mailpile/mailpile/mail_source/imap.py", line 500, in timed
    return RunTimed(timeout, *args, **kwargs)
  File "/home/pmeeke/gits/Mailpile/mailpile/util.py", line 948, in RunTimed
    RunTimedThread(func.__name__, work).run_timed(timeout)
  File "/home/pmeeke/gits/Mailpile/mailpile/util.py", line 937, in run_timed
    raise TimedOut('Timed out: %s' % self.name)
TimedOut: Timed out: mkconn

56f71678-0f136-169f=ImapMailSource:R Connection timed out
bg/log(50): <ImapMailSource(xxxxx@xxxxx.com, started 140691969488640)>: Idle: Connection timed out
```

Settings and passwords have been checked and double checked. One of the accounts which are now not working, where previously working the day before. But my gmail account seems still to be running fine. 
I also noticed that mailboxes seemed to just randomly appeared with no emails in them when previously their was quite a lot (this also includes the gmail account) . 

So far my tests show: 
- Zoho mail always timed out, never received email but could send. 
- Gmail seems to be running ok but lost a lot of emails which where previously downloaded.
- Yandex mail did work, then I loast my emails from the mailbox, then the connection started to time out.

**Comment by pmeeke** [comment] 2016-03-28 14:03
I reinstalled everything today. So far I just have zoho running and it seems to be running fine.

**Comment by pmeeke** [comment] 2016-03-29 12:39
So I have the three email accounts running, I believe my issues may be the same as #1407 for the zoho account. 
But the yandex account still seems to be a bit wonky. I cant seem to get any mails from the inbox to be viewable, when I browse to the mail box, click settings I notice the mailbox role is stated as `archive` so I change it to `inbox` and enable the tags to `display in sidebar` and `add messages to search engine` ,  I click save, the screen refreshes, and when I cgo back into the mailbox settings all the settings are deactivated again with the mailbox role back to `archive`.

**Comment by BjarniRunar** [comment] 2017-03-31 21:12
Sorry about the late response; I'm closing this since there aren't enough details here for me to reproduce and the trail has gone cold.

We have however fixed a bunch of issues in the meantime, so it's quite likely that this has been fixed. Note that #1407 was not actually a bug at all, but confusion about how Mailpile handles duplicate messages.

Thank you very much for testing and providing feedback, and again, I'm very sorry I didn't respond in a timely fashion.

**Closed by BjarniRunar** 2017-03-31 21:12 UTC
