### ISSUE TITLE
IMAP sync

### ISSUE THREAD

**Issue by comzeradd** [mailpile/Mailpile#1608] opened 2016-06-07 12:26 UTC
I setup mailpile with my IMAP server. Fetching emails with their current status (read/unread) works great, but not the other way around.

If I read an email this doesn't update its status on IMAP. If I read an email from another email client, mailpile still shows that as unread.

I'm on HEAD.

**Comment by mrbiber** [comment] 2016-09-21 10:06
Duplicate of #1017 (which has a bounty attached).

**Closed** 2016-09-21 11:06 UTC
