### ISSUE TITLE
 U function with non-root location does not add http_path to /crypto/tls/getcert/ route

### ISSUE THREAD

**Issue by foursixnine** [mailpile/Mailpile#2106] opened 2018-06-20 21:24 UTC
So while trying to use latest release and master from mailpile, I get into trouble when trying to use the    TLS Certificate Tool. Applying:  changes in  #2105 solved my problem.

When clicking the button, if aforementioned changes are not applied, `AM: Error: error` is shown in the JS console, `AM: Success!` is shown when changes are applied, and modal window shows up as expected. I used [this guide](https://github.com/mailpile/Mailpile/wiki/Accessing-The-GUI-Over-Internet#using-nginx-as-proxy) to set it up. Everything else seems to work without problems

Mailpile version: v1.0.0rc3 (Current master)

Nginx configuration for that host:
```
  location /c {
    access_log /var/log/nginx/mailpile_access.log;
    error_log /var/log/nginx/mailpile_error.log info;

    proxy_pass http://127.0.0.1:33411;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Server $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
```

Mailpile sys.http_path

```
mailpile> P sys.http_path
Elapsed: 0.001s (print: Displayed settings)

{
    "sys.http_path": "/c"
}

```
Screenshot without the changes:

![2018-06-20-230015_1065x745_scrot](https://user-images.githubusercontent.com/229240/41684454-c63c8270-74dd-11e8-9c79-20c7bec4ed1c.png)

With the changes everything works.

**Comment by BjarniRunar** [comment] 2018-06-21 09:59
Thank you for the detailed report! The problem is that `_url_path_fix` in `mailpile/www/jinjaextensions.py` checks if the URL startswith `prefix`, but doesn't ensure that it startswith `prefix/`. So it mistakenly thinks the URL `/crypto/.../` already has your prefix `/c` applied.

I am pretty sure the fix is to simply add a `+ '/'` to the if statement in `_url_path_fix`.

The exact same bug is also present in the equivalent Javascript code, `shared-data/default-theme/html/jsapi/index.js`: `if (original_url.indexOf(prefix) != 0)`.

Could you test and verify?

And if you'd like to get your PR merged, that would be the way to do it! Otherwise I'll get this fixed at my end next time I am ready to push.

**Comment by foursixnine** [comment] 2018-06-21 11:01
@BjarniRunar I will give it a shot later then :) Thanks for the explanation!

**Comment by BjarniRunar** [comment] 2018-07-26 14:33
That looks right to me, sorry about the late reply! If you want the credit, a PR would fit my work-flow and leave the appropriate "paper trail." Otherwise I can just duplicate it at my end.

**Comment by foursixnine** [comment] 2018-07-26 15:57
Cool I just reopen the old one

**Comment by foursixnine** [comment] 2018-07-26 16:00
@BjarniRunar No problems :) PR opened.

**Closed** 2018-07-28 16:14 UTC
Labels: Bugs
