### ISSUE TITLE
stuff from tests/data/Maildir in user inbox

### ISSUE THREAD

**Issue by victormatheus** [mailpile/Mailpile#1277] opened 2015-04-19 11:07 UTC
After I installed mailpile I got really surprised with some emails that didn't make sense. it turns out that test emails from tests/data/Maildir that got into my the inbox.

**Comment by BjarniRunar** [comment] 2015-06-05 22:38
I've installed Mailpile literally 100s of times and never seen this happen. :-)

That said, there are many ways a user could mistakenly add those folders; including but not limited to:

 - Local folder chosen during source setup, which is a parent of the folder containing Mailpile test data (the child folders will be added by default)
 - Dev test scripts run instead of the normal Mailpile script

These are not really bugs though, although the root cause (if my theory is correct) is indeed a major issue - the app is too confusing during setup, and it is easy to make a mistake.

I am working hard on improving this very thing right now, but this issue isn't the right place to track that work. So I'm going to close this; thank you for taking the time to file your report. Please feel free to reopen and add further details if you feel I've made a mistake.

**Closed by BjarniRunar** 2015-06-05 22:38 UTC
