### ISSUE TITLE
Imap Subfolders

### ISSUE THREAD

**Issue by funkytoad** [mailpile/Mailpile#1337] opened 2015-07-21 13:55 UTC
Beta III: I don't have access to any of my custom IMAP folders. 
Am I missing something?
I see some similar posts that are over a year old, but can't tell if it has been or will be addressed. Sadly I can't give mailpile a real try without my custom imap folders.

**Comment by BjarniRunar** [comment] 2015-07-28 12:52
Hello!  Thanks for filing.

There can be two explanations for this:

1) Mailpile's IMAP code failed to detect and add your folders
2) Mailpile did detect them and created tags, but the tags are not in the sidebar

Note that case 2) is by design, to avoid clutter. You could have changed this default setting by ticking the appropriate box during account setup.

You can verify whether it is case 1) or 2) by using the Browse interface (button to the lower-right of the account list) and browsing your IMAP server. If your folders are visible and you can edit their tag settings, then we have case 2) and this bug should be closed. If your folders are not found in the browser, then we have case 1) and I would like to work with you to debug and understand why our IMAP code is failing.

In case 2), if you want to make the tags visible, that should be possible using the edit dialog for the generated tags (accessible via Browse).

**Comment by funkytoad** [comment] 2015-07-28 13:28
Hello,
The Browse function does not show any of my folders. This is true for 2 accounts on the same server.
I did uncheck a setting to allow mailpile to make tags because I wasn't sure what the function meant.

I can't remove the accounts in order to see if recreating them would help leaving that option alone.

I will uninstall mailpile completely and try again, and report back. If it fails again I can create an email account for you with sub folders to test out on the same server if you'd like.

**Comment by funkytoad** [comment] 2015-07-28 13:50
Ah Ha! That did it. I need to check "create visible tags of all folders" during the account setup. Now I see the folders.

I guess the problem is the "browse" did not reveal the folders.

**Comment by BjarniRunar** [comment] 2015-07-28 18:41
Hmm. Did the browser show the imap servers and did you thoroughly browse their contents? You might have had to go a few levels down, some IMAP servers nest subfolders inside the INBOX.

**Comment by BjarniRunar** [comment] 2015-08-03 18:43
Closing this; please re-open if you can confirm that Mailpile actually failed to browse your IMAP correctly. :-)

**Closed by BjarniRunar** 2015-08-03 18:43 UTC
