### ISSUE TITLE
 Mailpile passphrase stops working after service restart

### ISSUE THREAD

**Issue by rzippert** [mailpile/Mailpile#1099] opened 2014-11-17 22:33 UTC
Hello everyone!

Mailpile installs perfectly with no issues. Account setup also works fine and it is able to download and send emails. After simply restarting the mailpile service though, no passphrase is accepted anymore.

Systemctl status -l mailpile:

```
* mailpile.service - Mailpile Daemon
   Loaded: loaded (/usr/lib/systemd/system/mailpile.service; enabled)
   Active: active (running) since Tue 2014-11-11 16:55:37 BRST; 30s ago
 Main PID: 2222 (python2)
   CGroup: /system.slice/mailpile.service
           `-2222 python2 /usr/bin/mp --www localhost:33411 wait

systemd[1]: Started Mailpile Daemon.
mp[2222]: Loaded language pt_BR
mp[2222]: [1.9K blob data]
mp[2222]: [394B blob data]
mp[2222]: [118B blob data]
mp[2222]: Traceback (most recent call last):
mp[2222]: File "/usr/share/mailpile/mailpile/crypto/gpgi.py", line 365, in writeout
mp[2222]: fd.write(line)
mp[2222]: IOError: [Errno 32] Broken pipe
mp[2222]: http://domain.net "POST /auth/login/?_path=%2F HTTP/1.0" 200 8839
```

Everytime I try to "login" with the passphrase the last 4 lines are repeated. Tried setting the whole /usr/share/mailpile/mailpile folder as 777 and owned by user mailpile to no avail. Complete removal and reinstall of the application, with even different setup doesn't change the behavior.

I tried a new setup (the same way I described above) to make sure and it's not about special characters or password length, unless 8 characters with uppercase, lowercase and number characters are a problem...

Also made sure to check if it worked before restarting the service, and it does. Logging out and then in again works as long as I haven't stopped and restarted the service since setup...
- This is the new example log with 3 attempts:

> ```
> systemd[1]: Started Mailpile Daemon.
> mp[7948]: Loaded language pt_BR
> mp[7948]: [1.9K blob data]
> mp[7948]: [394B blob data]
> mp[7948]: [118B blob data]
> mp[7948]: [368B blob data]
> mp[7948]: http://domain.net "GET /auth/login/?_path=%2F HTTP/1.0" 200 8740
> mp[7948]: http://domain.net "POST /auth/login/?_path=%2F HTTP/1.0" 200 8839
> mp[7948]: http://domain.net "POST /auth/login/?_path=%2F HTTP/1.0" 200 8839
> ```

Any suggestion on where to look? A friend said it looks like a thread safety issue. Mailpile is installed on a linux server, not my own machine.

Thanks

**Comment by rzippert** [comment] 2015-01-21 03:15
Well... Back at this problem. In my case gpg-agent was not running. I've run it as `gpg-agent --daemon --use-standard-socket` and tested again. Result was pretty much the same as before, but now I get that POST after the error.

		Jan 21 00:53:26 server mp[1951]: http://website.example "POST /auth/login/?_path=%2F HTTP/1.0" 200 8839
		Jan 21 00:53:26 server mp[1951]: IOError: [Errno 32] Broken pipe
		Jan 21 00:53:26 server mp[1951]: fd.write(line)
		Jan 21 00:53:26 server mp[1951]: File "/usr/share/mailpile/mailpile/crypto/gpgi.py", line 365, in writeout
		Jan 21 00:53:26 server mp[1951]: Traceback (most recent call last):
		Jan 21 00:53:24 server mp[1951]: http://website.example "GET /auth/login/?_path=%2F HTTP/1.0" 200 8740
		Jan 21 00:53:23 server mp[1951]: [368B blob data]
		Jan 21 00:53:13 server mp[1951]: [118B blob data]
		Jan 21 00:53:13 server mp[1951]: [394B blob data]
		Jan 21 00:53:13 server mp[1951]: [1.9K blob data]
		Jan 21 00:53:08 server mp[1951]: Loaded language pt_BR

Just as a side note, while the GET and POST messages show as http, this website is configured as https only...

This instance of mailpile has been installed automatically, like those wordpress installers from hosts. Installing it manually might be a way to fix it or certainly not? I don't know much but would like a direction to follow to solve this...

Thanks =)

**Comment by coeusite** [comment] 2015-02-15 05:12
I tested this issue on both Centos 7 and Debian 7.

For Debian 7, no issue occurs after manually installing and starting "gpg-agent --daemon --use-standard-socket".
For Centos 7, this issue does occur. I can confirm that gpg-agent is running.

I also checked the version of GnuPG. It shows 1.4x on Debian and 2.0x on Centos, which may cause this problem.

**Comment by BjarniRunar** [comment] 2015-02-19 17:55
OK. I'm classifying this one as "problems caused by gpg/gpg-agent/etc". Thank you all for the very detailed bug reports! Great stuff.

There are many such problems, I'm afraid, this is one of the deeper issues in the current code-base. Relates to #733 .

**Comment by al-Quaknaa** [comment] 2015-03-02 16:16
I've got the same problem, BTW. Gentoo linux, gpg 2.0.27. Don't know if there's any other useful info I can provide?

**Comment by BjarniRunar** [comment] 2015-06-11 22:49
Just a note to everyone on this thread - Mailpile does not currently work reliably with GnuPG 2.x! That may be improving with the latest changes, but in general all bets are off if Mailpile is not talking to GnuPG 1.4.x.

**Comment by BjarniRunar** [comment] 2016-01-16 13:00
I am going to close this as effectively a dup of #1133. Thank you for all the detailed bug reports!

**Closed** 2016-11-30 16:03 UTC
Labels: Back End
