### ISSUE TITLE
new mails are not shown in a thunderbird mbox file

### ISSUE THREAD

**Issue by pravi** [mailpile/Mailpile#1363] opened 2015-08-03 16:32 UTC
I browsed and added a thunderbird mbox file and it does not show any new mails. Do I have to browse to that folder everytime I open mailpile? I remember setting it as INBOX role and adding the tag to left bar.

**Comment by BjarniRunar** [comment] 2015-08-03 18:18
This should work - but I would need more details to understand why it is failing for you. Can you tell me more about your setup?

**Comment by pravi** [comment] 2015-08-03 18:22
It may be related to #1359 

I have a profile with outgoing configured via smtp and incoming local files. I browse to my thunderbird INBOX mbox file and ad it as INBOX role and tag it on left bar.

Its debian sid amd64 and mailpile master checked out yesterday. What other specific details you need?

**Comment by pravi** [comment] 2015-08-03 18:24
Last new mail is 14 hours ago on mailpile, but thunderbird has from a few minutes ago. Even this refresh happened after I browsed to the same mbox file again.

**Comment by BjarniRunar** [comment] 2015-08-03 18:30
Thanks! Could you show me the output of http://localhost:33411/settings/sources/as.json and http://localhost:33411/eventlog/incomplete/as.json ?

Note these will show some data about your account, including usernames and file paths, please edit if you want those kept confidential. Passwords should be suppressed already, but please double-check and don't take my word for it.

**Comment by pravi** [comment] 2015-08-03 19:08
http://localhost:33411/settings/sources/as.json
```
{
 "command": "print", 
 "elapsed": "0.002", 
 "event_id": "55bfbb95.0058f.64e4", 
 "message": "Displayed settings", 
 "result": {
  "sources": {
   "82a55bdde61": {
    "auth_type": "password", 
    "discovery": {
     "apply_tags": {
      "0000": "16"
     }, 
     "create_tag": true, 
     "guess_tags": true, 
     "local_copy": false, 
     "parent_tag": "17", 
     "paths": {}, 
     "policy": "unknown", 
     "process_new": true, 
     "visible_tags": false
    }, 
    "enabled": true, 
    "host": "", 
    "interval": 300, 
    "keepalive": false, 
    "mailbox": {
     "0001": {
      "apply_tags": {
       "0000": "", 
       "0001": "16"
      }, 
      "local": "", 
      "name": "pravi", 
      "path": "@0001", 
      "policy": "read", 
      "primary_tag": "18", 
      "process_new": true
     }, 
     "0002": {
      "apply_tags": {
       "0000": "16", 
       "0001": "b"
      }, 
      "local": "", 
      "name": "INBOX", 
      "path": "@0002", 
      "policy": "read", 
      "primary_tag": "19", 
      "process_new": true
     }, 
     "0003": {
      "apply_tags": {
       "0000": "16", 
       "0001": "g"
      }, 
      "local": "", 
      "name": "Sent-1", 
      "path": "@0003", 
      "policy": "read", 
      "primary_tag": "1a", 
      "process_new": true
     }
    }, 
    "name": "Local mailboxes", 
    "password": "(SUPPRESSED)", 
    "port": 993, 
    "post_command": "", 
    "pre_command": "", 
    "profile": "de555bde022", 
    "protocol": "local", 
    "username": ""
   }
  }
 }, 
 "state": {
  "cache_id": "", 
  "command_url": "/settings/", 
  "context": "", 
  "context_url": "/settings/", 
  "query_args": {
   "_method": "GET", 
   "arg": [
    "sources"
   ]
  }
 }, 
 "status": "success"
}
```

**Comment by pravi** [comment] 2015-08-03 19:10
http://localhost:33411/eventlog/incomplete/as.json
```
{
 "command": "eventlog", 
 "elapsed": "0.001", 
 "event_id": "55bfbc37.00592.64e4", 
 "message": "Found 2 events", 
 "result": {
  "count": 2, 
  "events": [
   {
    "data": {
     "counters": {
      "copied_messages": 0, 
      "indexed_messages": 15371, 
      "unknown_policies": 0
     }, 
     "have_unknown": false, 
     "id": "82a55bdde61", 
     "mailbox_state": {
      "0001": "1415083573/419550", 
      "0002": "-1/-1", 
      "0003": "-1/-1"
     }, 
     "name": "Local mailboxes", 
     "rescan": {
      "added": 0, 
      "batch_size": 0, 
      "complete": true, 
      "errors": [], 
      "mailbox_id": "0001", 
      "running": false, 
      "total": 0, 
      "updated": 0
     }, 
     "rescans": [
      [
       "0001", 
       0, 
       "0001: Indexed mailbox: ...mail/pravi (0 new, 0 updated)", 
       {
        "complete": true, 
        "new": 0, 
        "updated": 0
       }
      ], 
      [
       "0001", 
       0, 
       "0001: No new mail in: /var/mail/pravi", 
       {
        "complete": true
       }
      ]
     ]
    }, 
    "date": "Mon, 03 Aug 2015 19:07:06 -0000", 
    "event_id": "55bde02c.000a3.13fd", 
    "flags": "R", 
    "message": "No new mail at 00:37", 
    "private_data": {}, 
    "source": ".mail_source.local.LocalMailSource", 
    "ts": 1438628826.13855
   }, 
   {
    "data": {
     "elapsed": 0, 
     "output": "text", 
     "ui": "BackgroundInteraction"
    }, 
    "date": "Mon, 03 Aug 2015 16:17:28 -0000", 
    "event_id": "55bf9418.001bd.4e53", 
    "flags": "R", 
    "message": "rescan: Starting", 
    "private_data": {}, 
    "source": ".commands.Rescan", 
    "ts": 1438618648
   }
  ], 
  "ts": 1438628826.13855
 }, 
 "state": {
  "cache_id": "", 
  "command_url": "/eventlog/", 
  "context": "", 
  "context_url": "/eventlog/", 
  "query_args": {
   "_method": "GET", 
   "arg": [
    "incomplete"
   ]
  }
 }, 
 "status": "success"
}
```

**Comment by BjarniRunar** [comment] 2015-08-03 21:31
Interesting - I forgot to request http://localhost:33411/settings/sys.mailbox/as.json - but it looks like the mailboxes were correctly configured, but they're not being read for some reason. Perhaps the output from the above URL will shed some light, otherwise I'll have to think a bit.

I wonder if you'd have a chance to join IRC sometime so we could discuss in person? Us die-hard Mailpilers hang out on #mailpile on Freenode.

**Comment by pravi** [comment] 2015-08-04 06:19
http://localhost:33411/settings/sys.mailbox/as.json
```
{
 "command": "print", 
 "elapsed": "0.001", 
 "event_id": "55c0594b.0019a.1993", 
 "message": "Displayed settings", 
 "result": {
  "sys.mailbox": {
   "0000": "/Mailpile$/mail", 
   "0001": "/var/mail/pravi", 
   "0002": "/Home$/.thunderbird/jda/ImapMail/mail.autistici.org/INBOX", 
   "0003": "/Home$/.thunderbird/jda/ImapMail/mail.autistici.org/Sent-1"
  }
 }, 
 "state": {
  "cache_id": "", 
  "command_url": "/settings/", 
  "context": "", 
  "context_url": "/settings/", 
  "query_args": {
   "_method": "GET", 
   "arg": [
    "sys.mailbox"
   ]
  }
 }, 
 "status": "success"
}
```

**Comment by BjarniRunar** [comment] 2015-08-04 18:11
Interesting. Thanks for updating, I'll have a look at my end and see if I find any clues.

**Comment by BjarniRunar** [comment] 2015-08-06 15:45
Thanks to your detailed bug reports, I was able to reproduce the issue at my end and will be pushing a fix up later today. Please re-open the issue (the push will close it) if the problem persists! :-)

**Closed** 2015-08-06 16:25 UTC
