### ISSUE TITLE
Mails are accidentally merged into one conversation solely based on the subject

### ISSUE THREAD

**Issue by paulvt** [mailpile/Mailpile#422] opened 2014-02-03 10:12 UTC
I have two e-mails from two completely unrelated parties, one with subject "appointment" and the other with subject "RE: appointment"; they are merged into a single conversation. 

When I was trying to look at the "RE: appointment" mail for the appointment confirmation, which I was sure was in the Inbox, I couldn't see it and it confused me. Only when using the search feature with the to me known company name, I could find it again. (Of course once I know it is in the "appointment" conversation I can find it now, but that is besides the point.)

**Comment by BjarniRunar** [comment] 2015-08-06 21:13
This is effectively a duplicate of #353, closing. :-)

**Closed by BjarniRunar** 2015-08-06 21:13 UTC
Labels: Back End
